asflags-y += -I$(srctree)/ekernel/drivers/hal/source/sound/component/aw-alsa-utils \
             -DCONFIG_BUILTIN_WAV_FILE

obj-y += aplay.o
obj-y += arecord.o
obj-y += aduplex.o
obj-y += amixer.o
obj-y += common.o
obj-y += wav_parser.o
obj-y += audio_wav/audio_wav.o

