/* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.

 * Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
 * the the People's Republic of China and other countries.
 * All Allwinner Technology Co.,Ltd. trademarks are used with permission.

 * DISCLAIMER
 * THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
 * IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
 * IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
 * ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
 * ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
 * COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
 * YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.


 * THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
 * PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
 * THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
 * OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef __SUNXI_CE_H__
#define __SUNXI_CE_H__

#ifdef __cplusplus
extern "C" {
#endif

/*#define CE_DEBUG*/
/* For debug */
#if defined(CE_DEBUG)
#define CE_DBG(fmt, arg...) printf("%s()%d - "fmt, __func__, __LINE__, ##arg)
#else
#define CE_DBG(fmt, arg...) do{} while(0)
#endif
#define CE_ERR(fmt, arg...) printf("%s()%d - "fmt, __func__, __LINE__, ##arg)
/*ce irq*/
#define SUNXI_IRQ_CE	68	

#define CE_ALIGN_SIZE	0x4

#define AES_MIN_KEY_SIZE	16
#define AES_MAX_KEY_SIZE	32


#define AES_TYPE_ECB	0
#define AES_TYPE_CBC	1

/*define the return value for aes*/
typedef enum{
	AES_STATUS_OK = 0,
	AES_INPUT_ERROR = -1,
	AES_KEY_ERROR = -2,
	AES_CRYPTO_ERROR = -3,
	AES_TIME_OUT = -4,
} aes_status_t;

/*ce flow*/
#define CE_FLOW_NUM				4
#define CE_FLOW_AVAILABLE		0
#define CE_FLOW_UNAVAILABLE		1


#ifdef __cplusplus
}
#endif

#endif /* __SUNXI_CE_H__ */
