#
#config file for sun8iw18
#
#stroage
include $(TOPDIR)/board/sun8iw19p1/common.mk

MODULE=sboot

CFG_SUNXI_NAND =y
CFG_SUNXI_CE_20 =y
CFG_SUNXI_EFUSE =y

CFG_SUNXI_SBOOT =y

CFG_SUNXI_SPINOR_SPL_GPT=y
CFG_SPINOR_GPT_ARD=224
CFG_SUNXI_FREERTOS=y
CFG_SPINOR_FREERTOS_NAME_A="rtosA"
CFG_SPINOR_FREERTOS_NAME_B="rtosB"
CFG_SPINOR_ENV_NAME="env"
CFG_SPINOR_ENV_NAME_2="env-redund"
CFG_SUNXI_GUNZIP=y
CFG_SUNXI_LZ4=y
CFG_SPINOR_INDIVIDUAL_LOCK=y
