#
#config file for sun8iw19
#

include $(TOPDIR)/board/sun8iw19p1/common.mk
MODULE=spinor
CFG_SUNXI_SPINOR =y
CFG_SUNXI_SPI =y
CFG_SPINOR_UBOOT_OFFSET=128
CFG_SUNXI_SPINOR_SPL_GPT=y
CFG_SPINOR_GPT_ARD=96
CFG_SUNXI_FREERTOS=y
CFG_SPINOR_FREERTOS_NAME_A="bootA"
CFG_SPINOR_FREERTOS_NAME_B="bootB"
CFG_SPINOR_ENV=y
CFG_SPINOR_ENV_NAME="env"
CFG_SPINOR_ENV_NAME_2="env-redund"
CFG_SUNXI_GUNZIP=y
CFG_SUNXI_LZ4=y
CFG_SPINOR_INDIVIDUAL_LOCK=y
