# Audio Platform Common
obj-y += core/

# Sunxi Internal Codecs
obj-y += sunxi-codecs/

# Sunxi Daudio
obj-y += sunxi-i2s/

# Audio Utils
obj-y += component/

# Soundcards Register Select
obj-y += card_default.o

