subdir-ccflags-y += -I$(obj)/include/hal
subdir-ccflags-y += -I$(obj)/include/drv
subdir-ccflags-y += -I$(obj)/include/hal/sdmmc
subdir-ccflags-y += -I$(obj)/hal/source/osal/include

obj-y += drv/
obj-y += hal/
obj-y += test/
