subdir-ccflags-y +=	-I$(srctree)/ekernel/drivers/include/drv/
subdir-ccflags-y +=	-I$(srctree)/ekernel/drivers/subsys/libc/dlib/sys/
subdir-ccflags-y +=	-I$(srctree)/ekernel/drivers/include/hal/
subdir-ccflags-y +=	-I$(srctree)/ekernel/subsys/env/
subdir-ccflags-y +=	-I$(srctree)/ekernel/drivers/hal/source/osal/include/
subdir-ccflags-y +=	-I$(srctree)/ekernel/subsys/net/rt-thread/lwip/src/
subdir-ccflags-y +=	-I$(srctree)/ekernel/subsys/net/rt-thread/lwip/src/include/
subdir-ccflags-y +=	-I$(srctree)/ekernel/subsys/net/rt-thread/lwip/include/
subdir-ccflags-y +=	-I$(srctree)/ekernel/subsys/net/rt-thread/lwip/include/ipv4/
subdir-ccflags-y +=	-I$(srctree)/ekernel/subsys/net/rt-thread/lwip/src/arch/include/

obj-$(CONFIG_LWIP) += aw-ota.o
