DRIVERS_SDMMC_FREE_RTOS_OSAL_OBJECTS += $(BUILD_DIR)/drivers/chip-src/sdmmc/osal/os/FreeRTOS/os_debug.o
DRIVERS_SDMMC_FREE_RTOS_OSAL_OBJECTS += $(BUILD_DIR)/drivers/chip-src/sdmmc/osal/os/FreeRTOS/os_mutex.o
DRIVERS_SDMMC_FREE_RTOS_OSAL_OBJECTS += $(BUILD_DIR)/drivers/chip-src/sdmmc/osal/os/FreeRTOS/os_queue.o
DRIVERS_SDMMC_FREE_RTOS_OSAL_OBJECTS += $(BUILD_DIR)/drivers/chip-src/sdmmc/osal/os/FreeRTOS/os_semaphore.o
DRIVERS_SDMMC_FREE_RTOS_OSAL_OBJECTS += $(BUILD_DIR)/drivers/chip-src/sdmmc/osal/os/FreeRTOS/os_thread.o
DRIVERS_SDMMC_FREE_RTOS_OSAL_OBJECTS += $(BUILD_DIR)/drivers/chip-src/sdmmc/osal/os/FreeRTOS/os_timer.o


#KERNEL_FREERTOSXR871_OBJECTS += $(BUILD_DIR)/kernel/FreeRTOS/Source/portable/GCC/ARM_CA9/port.o
#KERNEL_FREERTOSXR871_OBJECTS += $(BUILD_DIR)/kernel/FreeRTOS/Source/portable/GCC/ARM_CA9/portASM.o

$(DRIVERS_SDMMC_FREE_RTOS_OSAL_OBJECTS):MODULE_NAME="FreeRTOSXR871"
$(DRIVERS_SDMMC_FREE_RTOS_OSAL_OBJECTS):CFLAGS += -I $(BASE)/include/drivers/
$(DRIVERS_SDMMC_FREE_RTOS_OSAL_OBJECTS):ASFLAGS += -I $(BASE)/include/drivers/
$(DRIVERS_SDMMC_FREE_RTOS_OSAL_OBJECTS):CFLAGS += -I $(BASE)/include/sys/
$(DRIVERS_SDMMC_FREE_RTOS_OSAL_OBJECTS):ASFLAGS += -I $(BASE)/include/sys/
$(DRIVERS_SDMMC_FREE_RTOS_OSAL_OBJECTS):CFLAGS += -I $(BASE)/kernel/FreeRTOS/Source/include/
$(DRIVERS_SDMMC_FREE_RTOS_OSAL_OBJECTS):ASFLAGS += -I $(BASE)/kernel/FreeRTOS/Source/include/
$(DRIVERS_SDMMC_FREE_RTOS_OSAL_OBJECTS):CFLAGS += -I $(BASE)/kernel/FreeRTOS/Source/
$(DRIVERS_SDMMC_FREE_RTOS_OSAL_OBJECTS):ASFLAGS += -I $(BASE)/kernel/FreeRTOS/Source/
$(DRIVERS_SDMMC_FREE_RTOS_OSAL_OBJECTS):CFLAGS += -I $(BASE)/kernel/FreeRTOS/Source/portable/GCC/ARM_CA9/
$(DRIVERS_SDMMC_FREE_RTOS_OSAL_OBJECTS):ASFLAGS += -I $(BASE)/kernel/FreeRTOS/Source/portable/GCC/ARM_CA9/
$(DRIVERS_SDMMC_FREE_RTOS_OSAL_OBJECTS):CFLAGS += -I $(BASE)/include/
$(DRIVERS_SDMMC_FREE_RTOS_OSAL_OBJECTS):ASFLAGS += -I $(BASE)/include/
$(DRIVERS_SDMMC_FREE_RTOS_OSAL_OBJECTS):CFLAGS += -I $(BASE)/include/drivers/chip/sdmmc/osal/
$(DRIVERS_SDMMC_FREE_RTOS_OSAL_OBJECTS):ASFLAGS += -I $(BASE)/include/drivers/chip/sdmmc/osal/
$(DRIVERS_SDMMC_FREE_RTOS_OSAL_OBJECTS):CFLAGS += -I $(BASE)/include/drivers/chip/sdmmc/osal/FreeRTOS/
$(DRIVERS_SDMMC_FREE_RTOS_OSAL_OBJECTS):ASFLAGS += -I $(BASE)/include/drivers/chip/sdmmc/osal/FreeRTOS/
$(DRIVERS_SDMMC_FREE_RTOS_OSAL_OBJECTS):CFLAGS += -I $(BASE)/
$(DRIVERS_SDMMC_FREE_RTOS_OSAL_OBJECTS):ASFLAGS += -I $(BASE)/
$(DRIVERS_SDMMC_FREE_RTOS_OSAL_OBJECTS):CFLAGS += -I $(BASE)/include/drivers/chip/sdmmc/sys/
$(DRIVERS_SDMMC_FREE_RTOS_OSAL_OBJECTS):ASFLAGS += -I $(BASE)/include/drivers/chip/sdmmc/sys/
$

OBJECTS += $(DRIVERS_SDMMC_FREE_RTOS_OSAL_OBJECTS)
