subdir-ccflags-y += -I$(srctree)/ekernel/drivers/include/drv/
subdir-ccflags-y += -I$(srctree)/ekernel/drivers/subsys/libc/dlib/sys/
subdir-ccflags-y += -I$(srctree)/ekernel/drivers/include/hal/
subdir-ccflags-y += -I$(srctree)/ekernel/drivers/hal/source/osal/include/

obj-$(CONFIG_COMPONENT_ENV) += env.o
