subdir-ccflags-y :=     -I$(srctree)/include/melis/board \
			-I$(srctree)/include/melis/kernel \
			-I$(srctree)/include/melis/module \
			-I$(srctree)/include/melis/libs/libc \
			-I$(srctree)/include/melis/libs/libc/misc
#obj-m += mod_slib/
