ccflags-y += 	-I$(obj)/ \
		-I$(srctree)/include/melis/kernel/drivers
obj-y += hal_clk.o
obj-y += hal_reset.o

obj-y += clk.o
obj-y += clk_factors.o
obj-y += clk_periph.o

obj-$(CONFIG_SOC_SUN8IW19P1) += sun8iw19p1/
obj-y += sun8iw19p1/
