subdir-ccflags-y += -I$(srctree)/ekernel/drivers/include/

obj-$(CONFIG_SUNXI_SPINOR_TEST) += test_spinor.o
obj-$(CONFIG_SUNXI_PART_TEST) += test_part.o
obj-$(CONFIG_SUNXI_IO_MULTIPLEX_TEST) += test_io_multiplex.o
obj-$(CONFIG_SUNXI_PWM_TEST) += test_pwm.o
obj-$(CONFIG_SUNXI_KEYBOARD_TEST) += test_keyboard.o
obj-$(CONFIG_SUNXI_GPIO_TEST) += test_gpio.o
obj-$(CONFIG_SUNXI_REGULATOR_TEST) += test_regulator.o
obj-$(CONFIG_SUNXI_TWI_TEST) += test_twi.o
obj-$(CONFIG_SUNXI_SPI_TEST) += test_spi.o
obj-$(CONFIG_SUNXI_RTC_TEST) += test_rtc.o
obj-$(CONFIG_SUNXI_UART_TEST) += test_uart.o
obj-$(CONFIG_SUNXI_USB_TEST) += usb/
obj-$(CONFIG_SUNXI_G2D_TEST) += test_g2d.o test_g2d_scale_job.o test_g2d_blend.o
obj-$(CONFIG_SUNXI_CE_TEST) += test_ce.o
obj-$(CONFIG_SUNXI_DISP2_TEST) += disp2/

obj-y += network/
